import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Transaction, CashEntry } from '../types';
import { formatCurrency, formatDate } from './calculations';

export const generateTransactionPDF = async (
  transactions: Transaction[],
  businessName: string,
  userName: string,
  reportTitle: string = 'Transaction Report'
): Promise<void> => {
  const totalLena = transactions.filter(t => t.type === 'lena').reduce((s, t) => s + t.amount_paisa, 0);
  const totalDena = transactions.filter(t => t.type === 'dena').reduce((s, t) => s + t.amount_paisa, 0);
  const netBalance = totalLena - totalDena;

  const html = `<!DOCTYPE html><html><head><style>
    body{font-family:Arial,sans-serif;padding:20px}
    .header{text-align:center;margin-bottom:30px}
    .header h1{color:#00A651;margin:0}
    .header p{color:#666;margin:5px 0}
    .summary{background:#f5f5f5;padding:15px;border-radius:8px;margin-bottom:20px}
    .summary-row{display:flex;justify-content:space-between;margin:5px 0}
    .summary-label{font-weight:bold;color:#333}
    .lena{color:#00A651}.dena{color:#dc2626}
    table{width:100%;border-collapse:collapse;margin-top:20px}
    th{background:#00A651;color:white;padding:12px;text-align:left}
    td{padding:10px;border-bottom:1px solid #ddd}
    tr:nth-child(even){background:#f9f9f9}
    .footer{margin-top:30px;text-align:center;color:#666;font-size:12px}
  </style></head><body>
    <div class="header">
      <h1>DigiKhata - ${reportTitle}</h1>
      <p>${businessName}</p><p>Generated by: ${userName}</p>
      <p>Date: ${new Date().toLocaleDateString('en-PK')}</p>
    </div>
    <div class="summary">
      <div class="summary-row"><span class="summary-label">Total Transactions:</span><span>${transactions.length}</span></div>
      <div class="summary-row"><span class="summary-label">Total Lena:</span><span class="lena">${formatCurrency(totalLena)}</span></div>
      <div class="summary-row"><span class="summary-label">Total Dena:</span><span class="dena">${formatCurrency(totalDena)}</span></div>
      <div class="summary-row"><span class="summary-label">Net Balance:</span><span class="${netBalance >= 0 ? 'lena' : 'dena'}">${formatCurrency(netBalance)}</span></div>
    </div>
    <table>
      <thead><tr><th>Date</th><th>Party Name</th><th>Type</th><th>Amount</th><th>Notes</th></tr></thead>
      <tbody>
        ${transactions.map(t => `
          <tr>
            <td>${formatDate(t.date)}</td>
            <td>${t.partyName}</td>
            <td class="${t.type === 'lena' ? 'lena' : 'dena'}">${t.type.toUpperCase()}</td>
            <td class="${t.type === 'lena' ? 'lena' : 'dena'}">${formatCurrency(t.amount_paisa)}</td>
            <td>${t.notes || '-'}</td>
          </tr>`).join('')}
      </tbody>
    </table>
    <div class="footer"><p>Generated by DigiKhata App</p></div>
  </body></html>`;

  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share Transaction Report' });
};

export const generateCashbookPDF = async (
  cashBook: CashEntry[],
  businessName: string,
  userName: string
): Promise<void> => {
  const totalIn = cashBook.filter(e => e.direction === 'in').reduce((s, e) => s + e.amount_paisa, 0);
  const totalOut = cashBook.filter(e => e.direction === 'out').reduce((s, e) => s + e.amount_paisa, 0);
  const balance = totalIn - totalOut;

  const html = `<!DOCTYPE html><html><head><style>
    body{font-family:Arial,sans-serif;padding:20px}
    .header{text-align:center;margin-bottom:30px}
    .header h1{color:#00A651;margin:0}
    .header p{color:#666;margin:5px 0}
    .summary{background:#f5f5f5;padding:15px;border-radius:8px;margin-bottom:20px}
    .summary-row{display:flex;justify-content:space-between;margin:5px 0}
    .summary-label{font-weight:bold;color:#333}
    .in{color:#00A651}.out{color:#dc2626}
    table{width:100%;border-collapse:collapse;margin-top:20px}
    th{background:#00A651;color:white;padding:12px;text-align:left}
    td{padding:10px;border-bottom:1px solid #ddd}
    tr:nth-child(even){background:#f9f9f9}
    .footer{margin-top:30px;text-align:center;color:#666;font-size:12px}
  </style></head><body>
    <div class="header">
      <h1>DigiKhata - Cash Book Report</h1>
      <p>${businessName}</p><p>Generated by: ${userName}</p>
      <p>Date: ${new Date().toLocaleDateString('en-PK')}</p>
    </div>
    <div class="summary">
      <div class="summary-row"><span class="summary-label">Total Entries:</span><span>${cashBook.length}</span></div>
      <div class="summary-row"><span class="summary-label">Total Cash In:</span><span class="in">${formatCurrency(totalIn)}</span></div>
      <div class="summary-row"><span class="summary-label">Total Cash Out:</span><span class="out">${formatCurrency(totalOut)}</span></div>
      <div class="summary-row"><span class="summary-label">Balance:</span><span class="${balance >= 0 ? 'in' : 'out'}">${formatCurrency(balance)}</span></div>
    </div>
    <table>
      <thead><tr><th>Date</th><th>Description</th><th>Direction</th><th>Amount</th></tr></thead>
      <tbody>
        ${cashBook.map(e => `
          <tr>
            <td>${formatDate(e.date)}</td>
            <td>${e.description}</td>
            <td class="${e.direction === 'in' ? 'in' : 'out'}">${e.direction.toUpperCase()}</td>
            <td class="${e.direction === 'in' ? 'in' : 'out'}">${formatCurrency(e.amount_paisa)}</td>
          </tr>`).join('')}
      </tbody>
    </table>
    <div class="footer"><p>Generated by DigiKhata App</p></div>
  </body></html>`;

  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share Cash Report' });
};

export const generateGenericPDF = async (
  title: string,
  data: Record<string, any>[],
  businessName: string = 'DigiKhata Business'
): Promise<void> => {
  if (data.length === 0) return;
  const headers = Object.keys(data[0]);

  const html = `<!DOCTYPE html><html><head><style>
    body{font-family:Arial,sans-serif;padding:20px}
    .header{text-align:center;margin-bottom:30px}
    .header h1{color:#2563eb;margin:0}
    .header p{color:#666;margin:5px 0}
    table{width:100%;border-collapse:collapse;margin-top:20px}
    th{background:#2563eb;color:white;padding:12px;text-align:left}
    td{padding:10px;border-bottom:1px solid #ddd}
    tr:nth-child(even){background:#f9f9f9}
    .footer{margin-top:30px;text-align:center;color:#666;font-size:12px}
  </style></head><body>
    <div class="header">
      <h1>${title}</h1>
      <p>${businessName}</p>
      <p>Generated on: ${new Date().toLocaleDateString()}</p>
    </div>
    <table>
      <thead>
        <tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr>
      </thead>
      <tbody>
        ${data.map(row => `
          <tr>
            ${headers.map(h => `<td>${row[h]}</td>`).join('')}
          </tr>
        `).join('')}
      </tbody>
    </table>
    <div class="footer"><p>Generated by DigiKhata App</p></div>
  </body></html>`;

  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `Share ${title}` });
};
